name: Execute Tests
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install dependencies
          run: npm install
        - name: Execute scripts
          run: newman run 'Dummy API.postman_collection.json'
